version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000

    volumes: 
      - ./:/usr/src/app:ro

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    env_file:
      - ./.env
    environment:
      # - database_hostname=dpg-d3o85ter433s739scfeg-a.oregon-postgres.render.com
      - database_hostname=postgres
      - database_port=5432
      - database_password=14hs1021
      - database_name=verifi
      - database_username=postgress
      - secret_key=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - algorithm=HS256
      - access_token_expire_minutes=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=14hs1021
      - POSTGRES_DB=fastapi
        
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: 